packages:
  - apps/**/*
  - packages/**/*

autoInstallPeers: false

catalog:
  vite: ^7.1.7
  "@esri/calcite-components": ^5.0.0

allowBuilds:
  "@vaadin/vaadin-usage-statistics": false
  core-js: false
  esbuild: true # doc: https://esbuild.github.io/getting-started/#additional-npm-flags
  sharp: false # astro image compression

blockExoticSubdeps: true
strictDepBuilds: true

engineStrict: true

minimumReleaseAge: 1440 # 1 day
minimumReleaseAgeExclude:
  - "@arcgis/*"
  - "@esri/*"
